GET http://localhost:3000/api/products

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "iPhone 12 Pro",
  "price": 999,
  "categoryId": 1
}

###
GET http://localhost:3000/api/products/4


###
DELETE http://localhost:3000/api/products/3


###
PATCH http://localhost:3000/api/products/4
Content-Type: application/json

{
  "name": "iPad Pro",
  "price": 1299,
  "categoryId": 2
}